import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {join} from 'node:path';
import {createSearchService} from '../scripts/search-service.mjs';
import {collectSources,extractiveDataset,applyGroundedAnalysis,safeSourceUrl} from '../scripts/song-data.mjs';
const saved=JSON.parse(await readFile(new URL('../data/sources.json',import.meta.url),'utf8'));
const items=saved.sources.map(s=>({Title:s.title,AuthorName:s.author,ContentType:s.type,Url:s.url,ContentText:s.texts.find(t=>t.id===s.frequencyTextId).text,CommentInfoList:[{Content:'测试排除评论，不得保存'}]}));
const historicalResponse={Code:0,Data:{Items:items}};
const quota={Code:0,Data:[{APIID:'zhihu_search',RemainingQuota:10,TotalQuota:10}]};
const query='《反乌托邦》 音乐评价';
async function make(provider){const dir=await mkdtemp(join(tmpdir(),'songwall-service-'));return {dir,runtimeDir:pathToFileURL(dir+'/'),service:createSearchService({provider,runtimeDir:pathToFileURL(dir+'/')})};}
test('cached preset never calls provider; new presets honestly pending',async()=>{const ctx=await make(()=>{throw Error('不应调用');});try{const result=await ctx.service.search({query:'反乌托邦'});assert.equal(result.cached,true);assert.equal(result.dataset.sources.length,saved.sources.length);const cat=await ctx.service.getCatalog();assert.equal(cat.songs.filter(s=>s.status==='ready').length,1);assert.equal(cat.songs.find(s=>s.id==='i-love-u').sourceCount,0);}finally{await rm(ctx.dir,{recursive:true});}});
test('recorded real-source fixture: unknown query → filter → extractive fallback → persisted cache',async()=>{const calls=[],stages=[];const ctx=await make(async args=>{calls.push(args[0]);if(args[0]==='quota')return quota;if(args[0]==='search')return historicalResponse;throw Error('测试模拟分析服务不可用');});try{const r=await ctx.service.search({query},{onProgress:p=>stages.push(p.stage)});assert.equal(r.cached,false);assert.equal(r.dataset.sources.length,saved.sources.length);assert(r.dataset.keywords.length>=2);assert.equal(r.dataset.analysisMode,'extractive');assert(r.dataset.analyses.every(a=>a.summaryKind==='extractive'&&a.status==='insufficient'));assert(r.dataset.sources.every(s=>!s.texts));assert(!JSON.stringify(r.dataset).includes('测试排除评论'));assert.deepEqual(stages,['cache','search','filter','analysis']);assert.equal((await ctx.service.search({query})).cached,true);assert.deepEqual(calls,['quota','search','answer']);const restart=createSearchService({provider:()=>{throw Error('不得请求');},runtimeDir:ctx.runtimeDir});assert.equal((await restart.search({query})).cached,true);}finally{await rm(ctx.dir,{recursive:true});}});
test('recorded AI-analysis fixture must pass original-quote validation; invented quotes are rejected',async()=>{const ctx=await make(async args=>args[0]==='quota'?quota:args[0]==='search'?historicalResponse:{choices:[{message:{content:JSON.stringify({keywords:saved.keywords.map(k=>({...k,patterns:k.frequency.patterns})),analyses:saved.analyses})}}]});try{const r=await ctx.service.search({query});assert.equal(r.dataset.analysisMode,'ai');assert(r.dataset.analyses.length>10);assert(r.dataset.analyses.every(a=>a.sourceUrl===r.dataset.sources.find(s=>s.id===a.sourceId).url));const base=extractiveDataset({title:'反乌托邦'},collectSources(items,{title:'反乌托邦'},new Date().toISOString()).sources,[],new Date().toISOString());assert.throws(()=>applyGroundedAnalysis(base,{keywords:[{id:'x',label:'音乐',patterns:['音乐']}],analyses:[{sourceId:'s1',keywordId:'x',quote:'不存在的原句',summary:'伪造',context:'',voice:'作者',status:'sufficient'}]}));}finally{await rm(ctx.dir,{recursive:true});}});
test('exhausted quota prevents business calls; invalid input never reaches CLI',async()=>{let calls=0;const ctx=await make(async args=>{calls++;assert.equal(args[0],'quota');return {Code:0,Data:[{APIID:'zhihu_search',RemainingQuota:0,TotalQuota:10}]};});try{await assert.rejects(()=>ctx.service.search({query:'白石溪',presetId:'baishixi'}),e=>e.code==='QUOTA_EXHAUSTED');await assert.rejects(()=>ctx.service.search({query:'I LOVE U',presetId:'i-love-u'}),e=>e.code==='QUOTA_EXHAUSTED');assert.equal(calls,1);await assert.rejects(()=>ctx.service.search({query:'\n'}),e=>e.code==='INVALID_QUERY');await assert.rejects(()=>ctx.service.search({query:'白石溪',presetId:'not-real'}),e=>e.code==='INVALID_QUERY');assert.equal(calls,1);}finally{await rm(ctx.dir,{recursive:true});}});
test('unrelated, anonymous, duplicate and unsafe links excluded; comments not used',()=>{const result=collectSources([{...items[0],AuthorName:''},{...items[0],Url:'https://attacker.invalid/x'},{...items[0],ContentText:'很短'},...items,items[0]],{title:'反乌托邦'},new Date().toISOString());assert.equal(result.sources.length,saved.sources.length);assert(result.excluded.length>=3);assert.equal(collectSources(items,{title:'白石溪'},new Date().toISOString()).sources.length,0);assert.equal(safeSourceUrl('https://www.zhihu.com.evil.test/answer/1'),false);assert.equal(safeSourceUrl('javascript:alert(1)'),false);});
test('quota increase is detected after short cache expiry, without waiting for tomorrow',async()=>{
 let now=Date.now(),quotaCalls=0,searchCalls=0;const ctx=await make(()=>{});
 const service=createSearchService({runtimeDir:ctx.runtimeDir,now:()=>now,provider:async args=>{
  if(args[0]==='quota'){quotaCalls++;return {Code:0,Data:[{APIID:'zhihu_search',RemainingQuota:quotaCalls===1?0:5000,TotalQuota:5000}]};}
  if(args[0]==='search'){searchCalls++;return historicalResponse;}throw Error('分析不可用的测试场景');
 }});
 try{await assert.rejects(()=>service.search({query}),e=>e.code==='QUOTA_EXHAUSTED');now+=300001;const r=await service.search({query});assert.equal(r.cached,false);assert.equal(quotaCalls,2);assert.equal(searchCalls,1);}finally{await rm(ctx.dir,{recursive:true});}
});
test('cancellation releases busy state without saving incomplete results',async()=>{let searchCount=0;const ctx=await make((args,{signal}={})=>{if(args[0]==='quota')return quota;if(args[0]==='search'){searchCount++;return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(Error('cancelled'),{code:'CANCELLED'})),{once:true}));}throw Error('not reached');});try{const controller=new AbortController();const result=ctx.service.search({query},{signal:controller.signal});while(searchCount===0)await new Promise(r=>setTimeout(r,5));await assert.rejects(()=>ctx.service.search({query:'白石溪'}),e=>e.code==='BUSY');controller.abort();await assert.rejects(result,e=>e.code==='CANCELLED');assert.equal((await ctx.service.getCatalog()).songs.length,3);}finally{await rm(ctx.dir,{recursive:true});}});
